### ISSUE TITLE
最小算力的单位会跟随实际算力变化的问题

### ISSUE THREAD

**Issue by 7351341** [dpkeeper/antminer-monitor#7]
设备会自动更改某一些IP的机器最小算力

**Comment by dpkeeper** [comment]
这个是正常功能和已知问题，当最小算力远小于实际算力时，会自动提高最小算力。目前的问题是当实际算力从GH下降到MH时，数字看起来增大了最小算力就跟着增大，但单位依旧沿用的GH，就出问题了。

**Comment by dpkeeper** [comment]
比如：最小算力被重设成了10GH时，实际算力下降到900MH，最小算力也变成了10MH，900MH > 10MH，矿机不会被重启

**Comment by dpkeeper** [comment]
v1.0.3
